### ISSUE TITLE
Share credential data on social media

### ISSUE THREAD

**Issue by sairanjit** [credebl/adeya-wallet#121]
## Summary

- Share Credential on Social Media

## Tasks

| Title                                                                                                                   | Assignees        | Status   |
| ----------------------------------------------------------------------------------------------------------------------- | ---------------- | -------- |
| [Finalize the flow](https://github.com/credebl/adeya-wallet/issues/)                                                    | [Sai Ranjit]     | Open     |
| [Use template to map the credential data in certificate template](https://github.com/credebl/adeya-wallet/issues/)      | [Sai Ranjit]     | Open     |
| [Share credential data to social media](https://github.com/credebl/adeya-wallet/issues/)                                | [Sai Ranjit]     | Open     |

[Sai Ranjit]: @sairanjit

**Comment by poonam-ghewande** [comment]
completed social share credential data.
