### ISSUE TITLE
Update  "ADEYA" logo on "Enter Pin" screen

### ISSUE THREAD

**Issue by poonam-ghewande** [credebl/adeya-wallet#162]
- [x] Update ADEYA logo on Enter PIN screen

**Comment by ashwini-aher** [comment]
As tested on the Android "**ADEYA_11_DEC.apk**" build and changes look fine.


![Image](https://github.com/credebl/adeya-wallet/assets/126259838/841e1463-5fdc-482d-b78c-dff2b8a3720a)

**Comment by poonam-ghewande** [comment]
Updated ADEYA logo on Enter PIN screen.

**Comment by poonam-ghewande** [comment]
Updated ADEYA logo on Enter PIN screen.
