### ISSUE TITLE
Building on XCode 16 `/node_modules/react-native-zip-archive/ios/RNZipArchive.m unsupported option '-G' for target 'arm64-apple-ios14.0-simulator'`

### ISSUE THREAD

**Issue by andorsk** [credebl/adeya-wallet#220]
**Describe the bug**
I was trying to build the app from scratch, and ran into the following issue on XCode 16 ios target:

`/node_modules/react-native-zip-archive/ios/RNZipArchive.m unsupported option '-G' for target 'arm64-apple-ios14.0-simulator'`

Which seems to be a bug related to https://github.com/mockingbot/react-native-zip-archive/issues/307. XCode 16. 

**To Reproduce**
1. Download Xcode 16
```sh
xcodebuild -version
Xcode 16.0
Build version 16A242d
```
2. Open project in XCode
3. Click run. Output should show 
```
/Users/andor/workspace/github.com/gan/demo/client-demo/adeya-fork/node_modules/react-native-zip-archive/ios/RNZipArchive.m unsupported option '-G' for target 'arm64-apple-ios11.0-simulator'
```
<img width="265" alt="image" src="https://github.com/user-attachments/assets/204eda4b-7dfd-4e37-91a6-4890d35de544">

**Expected behavior**
After steps 1-2, 3 should build the project.

**Logs**

> ScanDependencies /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.o /Users/andor/workspace/github.com/gan/demo/client-demo/adeya-fork/node_modules/react-native-zip-archive/ios/RNZipArchive.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNZipArchive' from project 'Pods')
>     cd /Users/andor/workspace/github.com/gan/demo/client-demo/adeya-fork/ios/Pods
>     
>     Using response file: /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/e6072d4f65d7061329687fe24e3d63a7-common-args.resp
>     
>     builtin-ScanDependencies -o /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.o.scan -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -ivfsstatcache /Users/andor/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.0-22A3362-db63dc9361471f152f572502bdbfe70a.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/andor/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Index.noindex/DataStore @/Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/e6072d4f65d7061329687fe24e3d63a7-common-args.resp -GCC_PREPROCESSOR_DEFINITIONS\=HAVE_INTTYPES_H\ HAVE_PKCRYPT\ HAVE_STDINT_H\ HAVE_WZAES\ HAVE_ZLIB\ MZ_ZIP_NO_SIGNING\  -include /Users/andor/workspace/github.com/gan/demo/client-demo/adeya-fork/ios/Pods/Target\ Support\ Files/RNZipArchive/RNZipArchive-prefix.pch -MMD -MT dependencies -MF /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.d --serialize-diagnostics /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.dia -c /Users/andor/workspace/github.com/gan/demo/client-demo/adeya-fork/node_modules/react-native-zip-archive/ios/RNZipArchive.m -o /Users/andor/Library/Developer/Xcode/DerivedData/AdeyaWallet-evguykojuobejcfsuymkiudslpqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/arm64/RNZipArchive.o
> 
> error: unsupported option '-G' for target 'arm64-apple-ios11.0-simulator' (in target 'RNZipArchive' from project 'Pods')

**Desktop (please complete the following information):**
- MacBook Pro 14 in 
 - OS: 14.6 Beta (23G5061b)
 - XCode Version: 
 ```sh
(base) andor@magic-pro-3 adeya-fork % xcodebuild -version
Xcode 16.0
Build version 16A242d
```

**Smartphone (please complete the following information):**
Targeting iPad Pro 13 in M4 ios 17.4 

**Additional context**

**Comment by andorsk** [comment]
Also related: https://stackoverflow.com/questions/78608693/boringssl-grpc-unsupported-option-g-for-target-arm64-apple-ios15-0

**Comment by andorsk** [comment]
My workaround in the `Podfile` got me through it.

```sh
installer.pods_project.targets.each do |target|
      if target.name == 'RNZipArchive'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            file.settings['COMPILER_FLAGS'] = ''
          end
        end
      end
    end
```

**Comment by sairanjit** [comment]
@andorsk Thanks for looking into the issue.I think we can fix this by updating the `react-native-zip-archive` package and increase the `min_ios_supported_version`

**Comment by sairanjit** [comment]
I am closing this issue as this is fixed now

**Comment by mac00048** [comment]
> I am closing this issue as this is fixed now

I am facing the same issue for my iOS project. Let me know which was helpful for you please.

**Comment by mac00048** [comment]
> My workaround in the `Podfile` got me through it.
> 
> ```shell
> installer.pods_project.targets.each do |target|
>       if target.name == 'RNZipArchive'
>         target.source_build_phase.files.each do |file|
>           if file.settings && file.settings['COMPILER_FLAGS']
>             file.settings['COMPILER_FLAGS'] = ''
>           end
>         end
>       end
>     end
> ```

Thank you.
May I just add this part to my podfile?
