### ISSUE TITLE
Apply logos/icons and color of ADEYA ( new ADEYA(react-native version))

### ISSUE THREAD

**Issue by poonam-ghewande** [credebl/adeya-wallet#38]
- [x] Apply logos/icons and color 
- [x] Apply implemented onboarding  page changes in ADEYA  
- [x] Apply implemented Home page changes in ADEYA

**Comment by sunilbade** [comment]
I have tested the Home screen and reported issue 
Bug: Bug(ADEYA): Contact count not increasing after connecting with organization.
link: https://github.com/credebl/automation-test-suite/issues/100

**Comment by sayali-chavan96** [comment]
I have tested the logo/icons and implementation of onboarding pages and changes look fine

1.Resolved issue: Bug(ADEYA): On the share securely page screen, "your privacy" text is missing


![Image](https://github.com/credebl/adeya-wallet/assets/133863994/f9eb9d5a-e544-48ef-b85a-26d428e1ce97)

2.Resolved issue: Bug(ADEYA): On the "Biometrics" page screen, displayed some extra content



![Image](https://github.com/credebl/adeya-wallet/assets/133863994/8cf385b9-0f69-404b-921d-449f26683189)

**Comment by sayali-chavan96** [comment]
Tested the Home screen and changes look fine
Resolved issue: Bug(ADEYA): Contact count not increasing after connecting with organization.


![Image](https://github.com/credebl/adeya-wallet/assets/133863994/5a42136a-d586-43d6-a284-1b76898680f8)
