### ISSUE TITLE
Support W3C credentials(JSON-LD credential format) in ADEYA

### ISSUE THREAD

**Issue by poonam-ghewande** [credebl/adeya-wallet#39]
- [x] Update agent setup option to Support W3C credentials
- [x] Add a new component to show and accept W3C credentials
- [x] Create W3C card component - Credential list
- [x] W3C credential details screen
- [x] Handle both indy and W3C credentials navigation
- [x] Test with multiple JSON-LD schemas
- [ ] Test end-to-end flow with issuer/CREDEBL

**Comment by sairanjitAW** [comment]
#45

**Comment by sairanjitAW** [comment]
Currently, we are not implementing the deletion of the JSON-LD credential as there is a limitation in the aries-framework-javascript 

https://github.com/hyperledger/aries-framework-javascript/blob/4856b8f6632a4d10faeb1b156397226b64e3b8b6/packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts#L384-L386
