### ISSUE TITLE
Add Random Name in while creating Wallet ADEYA and give option to user to change name

### ISSUE THREAD

**Issue by poonam-ghewande** [credebl/adeya-wallet#47]
- [x] Finalize design of Adding random name in Naming wallet screen ADEYA
- [x] Design naming of wallet screen as per figma
- [x] end-to-end testing

**Comment by poonam-ghewande** [comment]
- [ ]  Finalize design of Adding  email Id In Naming wallet screen ADEYA.

**Comment by amitayanworks** [comment]
As discussed, the wallet name should be Random with unique key.
Reference 

![Image](https://github.com/credebl/adeya-wallet/assets/142207827/92d6f596-edc4-4273-8234-6cbc086b23e1)

https://dashboard.trinsic.id/ecosystem

**Comment by poonam-ghewande** [comment]
created naming of wallet format  as per given format .

**Comment by poonam-ghewande** [comment]
random  wallet name visible on  credebl 

![Image](https://github.com/credebl/adeya-wallet/assets/133869533/827c0e7c-0ec1-42b5-a24c-13032782acbd)

**Comment by poonam-ghewande** [comment]
as per discussion with Amit and Girish  ,I have took task  for wallet naming screen  design .  
designed  wallet name  screen as mention below screenshot , please let me know any concern with it  .right now user can also also edit wallet name before intializing  Agent.
Also had discussion with Amit  & got requirement update regarding Edit  wallet  name  after initialization of wallet  user can edit wallet name which need to add in setting option of ADEYA  .  

![Image](https://github.com/credebl/adeya-wallet/assets/133869533/b001bac6-d034-41af-8dc0-42df5228d1fc)



![Image](https://github.com/credebl/adeya-wallet/assets/133869533/96e67a2a-8fc6-4ad2-8dbf-0dabf3f09e1e)
