### ISSUE TITLE
Add options to rename the ADEYA Wallet name

### ISSUE THREAD

**Issue by amitayanworks** [credebl/adeya-wallet#54]
- [x] Development should be based on approved Figma design.
- [x] User will got to Setting
- [x] Check the Wallet Name
- [x] Edit option button to rename wallet name
- [x] Notification to user before submitting
- [x] Once submitted, the change should reflect to new connection

**Comment by poonam-ghewande** [comment]
Added  option to rename the ADEYA wallet name , mention below in screenshot


![Image](https://github.com/credebl/adeya-wallet/assets/133869533/69171aea-9005-4213-90b2-17f6ea7da56b)

**Comment by poonam-ghewande** [comment]
the change should to new connection as  below mention screenshot.

![Image](https://github.com/credebl/adeya-wallet/assets/133869533/8b76141a-5038-4ed9-ae4e-272decf86780)

 

![Image](https://github.com/credebl/adeya-wallet/assets/133869533/7bfaf30a-ed8e-4b73-8689-334a9eb81324)
