### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by sairanjit** [credebl/adeya-wallet#84]
## Summary
- Add support for push notifications in a wallet with fcm

| Title                                           | Assignees | Milestone | Status  |
|--------------------------------------|:--------------:|------------------:|---------|
| [Add android config in wallet](https://github.com/credebl/adeya-wallet/issues/88) | [Poonam] | Sprint 8 | Todo |
| [Add iOS config in wallet](https://github.com/credebl/adeya-wallet/issues/89) | [Poonam] | Sprint 8 | Todo |
| [Add Aries RFC fcm in mediator](https://github.com/credebl/adeya-wallet/issues/85) | [Sai Ranjit] | Sprint 8 | Todo |
| [Setup firebase and send notifications to mobile app from mediator](https://github.com/credebl/adeya-wallet/issues/106) | [Sai Ranjit] | Sprint 8 | Todo |

[Sai Ranjit]: @sairanjit
[Poonam]: @poonam-ghewande

**Comment by poonam-ghewande** [comment]
Completed above epic.
